# -*- coding: utf-8 -*-
"""Clustering with K _Means

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Md1uO0q7ZGnWL23w7ba4s9R5e3NJIyi
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("Mall_Customers.csv")
print(df.head())
print(df.info())

import matplotlib.pyplot as plt
import seaborn as sns
sns.pairplot(df)
plt.suptitle("Pairplot of Customer Features", y=1.02)
plt.show()

from sklearn.cluster import KMeans

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(df)
    inertia.append(kmeans.inertia_)

# Plot the elbow curve
plt.plot(K, inertia, 'bo-')
plt.xlabel("Number of clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

# Assume K=5 from elbow method
kmeans = KMeans(n_clusters=5, random_state=42)
df['Cluster'] = kmeans.fit_predict(df)

print(df.head())

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
reduced_data = pca.fit_transform(df.drop('Cluster', axis=1))

plt.figure(figsize=(8,6))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=df['Cluster'], cmap='rainbow')
plt.title("Customer Segments after K-Means Clustering")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.colorbar(label='Cluster')
plt.show()

from sklearn.metrics import silhouette_score

score = silhouette_score(df.drop('Cluster', axis=1), df['Cluster'])
print(f"Silhouette Score: {score:.2f}")